
name: Fetch Raw Data

on:
  schedule:
    - cron: "0 3 * * 1" # cada lunes a las 03:00 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python src/etl/fetch_real_sources.py
      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/raw/*
          git commit -m "chore: update raw data" || echo "No cambios"
          git push
